import { Poppins, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Main from "@/components/Main";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "next-themes";
const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${poppins.variable} h-[100vw] antialiased`}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                >
                    <Navbar />
                    <Main>{children}</Main>
                </ThemeProvider>
            </body>
        </html>
    );
}
